export const LAY_DANH_SACH_KHOA_HOC = "LAY_DANH_SACH_KHOA_HOC";
export const LAY_DANH_MUC_KHOA_HOC = "LAY_DANH_MUC_KHOA_HOC";
export const MA_NHOM = "GP01";
export const LAY_KHOA_HOC_THEO_DANH_MUC = "LAY_KHOA_HOC_THEO_DANH_MUC";
